# Generated by Django 3.1.5 on 2021-01-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'project2 사용자', 'verbose_name_plural': 'project2 사용자들'},
        ),
    ]
